//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresTrust.DevExReports.API.PredefinedReports.Historic {
    
    public partial class EasementTemplate : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "PresTrust.DevExReports.API.PredefinedReports.Historic.EasementTemplate.repx");

            // Controls
            this.TopMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("TopMargin");
            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");
            this.BottomMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("BottomMargin");
            this.ReportHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportHeaderBand>("ReportHeader");
            this.PageFooter = reportInitializer.GetControl<DevExpress.XtraReports.UI.PageFooterBand>("PageFooter");
            this.richText17 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("richText17");
            this.pageBreak16 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageBreak>("pageBreak16");
            this.richText16 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("richText16");
            this.pageBreak15 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageBreak>("pageBreak15");
            this.richText15 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("richText15");
            this.pageBreak14 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageBreak>("pageBreak14");
            this.richText14 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("richText14");
            this.pageBreak13 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageBreak>("pageBreak13");
            this.richText13 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("richText13");
            this.pageBreak12 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageBreak>("pageBreak12");
            this.richText12 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("richText12");
            this.pageBreak11 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageBreak>("pageBreak11");
            this.richText11 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("richText11");
            this.pageBreak10 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageBreak>("pageBreak10");
            this.richText10 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("richText10");
            this.pageBreak9 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageBreak>("pageBreak9");
            this.richText9 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("richText9");
            this.pageBreak8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageBreak>("pageBreak8");
            this.richText8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("richText8");
            this.pageBreak7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageBreak>("pageBreak7");
            this.richText7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("richText7");
            this.pageBreak6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageBreak>("pageBreak6");
            this.richText6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("richText6");
            this.pageBreak5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageBreak>("pageBreak5");
            this.richText5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("richText5");
            this.pageBreak4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageBreak>("pageBreak4");
            this.richText4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("richText4");
            this.pageBreak3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageBreak>("pageBreak3");
            this.richText3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("richText3");
            this.pageBreak2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageBreak>("pageBreak2");
            this.richText2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("richText2");
            this.pageBreak1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageBreak>("pageBreak1");
            this.richText1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("richText1");
            this.label97 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label97");
            this.pageInfo2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageInfo>("pageInfo2");
            this.pictureBox2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPictureBox>("pictureBox2");
            this.label60 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label60");
            this.line2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("line2");

            // Parameters
            this.parambloburl = reportInitializer.GetParameter("parambloburl");

            // Data Sources
            this.sqlDataSource1 = reportInitializer.GetDataSource<DevExpress.DataAccess.Sql.SqlDataSource>("sqlDataSource1");

            // Calculated Fields
            this.AppId = reportInitializer.GetCalculatedField("AppId");
        }
        private DevExpress.XtraReports.UI.TopMarginBand TopMargin;
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.BottomMarginBand BottomMargin;
        private DevExpress.XtraReports.UI.ReportHeaderBand ReportHeader;
        private DevExpress.XtraReports.UI.PageFooterBand PageFooter;
        private DevExpress.XtraReports.UI.XRRichText richText17;
        private DevExpress.XtraReports.UI.XRPageBreak pageBreak16;
        private DevExpress.XtraReports.UI.XRRichText richText16;
        private DevExpress.XtraReports.UI.XRPageBreak pageBreak15;
        private DevExpress.XtraReports.UI.XRRichText richText15;
        private DevExpress.XtraReports.UI.XRPageBreak pageBreak14;
        private DevExpress.XtraReports.UI.XRRichText richText14;
        private DevExpress.XtraReports.UI.XRPageBreak pageBreak13;
        private DevExpress.XtraReports.UI.XRRichText richText13;
        private DevExpress.XtraReports.UI.XRPageBreak pageBreak12;
        private DevExpress.XtraReports.UI.XRRichText richText12;
        private DevExpress.XtraReports.UI.XRPageBreak pageBreak11;
        private DevExpress.XtraReports.UI.XRRichText richText11;
        private DevExpress.XtraReports.UI.XRPageBreak pageBreak10;
        private DevExpress.XtraReports.UI.XRRichText richText10;
        private DevExpress.XtraReports.UI.XRPageBreak pageBreak9;
        private DevExpress.XtraReports.UI.XRRichText richText9;
        private DevExpress.XtraReports.UI.XRPageBreak pageBreak8;
        private DevExpress.XtraReports.UI.XRRichText richText8;
        private DevExpress.XtraReports.UI.XRPageBreak pageBreak7;
        private DevExpress.XtraReports.UI.XRRichText richText7;
        private DevExpress.XtraReports.UI.XRPageBreak pageBreak6;
        private DevExpress.XtraReports.UI.XRRichText richText6;
        private DevExpress.XtraReports.UI.XRPageBreak pageBreak5;
        private DevExpress.XtraReports.UI.XRRichText richText5;
        private DevExpress.XtraReports.UI.XRPageBreak pageBreak4;
        private DevExpress.XtraReports.UI.XRRichText richText4;
        private DevExpress.XtraReports.UI.XRPageBreak pageBreak3;
        private DevExpress.XtraReports.UI.XRRichText richText3;
        private DevExpress.XtraReports.UI.XRPageBreak pageBreak2;
        private DevExpress.XtraReports.UI.XRRichText richText2;
        private DevExpress.XtraReports.UI.XRPageBreak pageBreak1;
        private DevExpress.XtraReports.UI.XRRichText richText1;
        private DevExpress.XtraReports.UI.XRLabel label97;
        private DevExpress.XtraReports.UI.XRPageInfo pageInfo2;
        private DevExpress.XtraReports.UI.XRPictureBox pictureBox2;
        private DevExpress.XtraReports.UI.XRLabel label60;
        private DevExpress.XtraReports.UI.XRLine line2;
        private DevExpress.DataAccess.Sql.SqlDataSource sqlDataSource1;
        private DevExpress.XtraReports.UI.CalculatedField AppId;
        private DevExpress.XtraReports.Parameters.Parameter parambloburl;
    }
}
