//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresTrust.DevExReports.API.PredefinedReports.Historic {
    
    public partial class EasementTemplate : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "PresTrust.DevExReports.API.PredefinedReports.Historic.EasementTemplate.repx");

            // Controls
            this.TopMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("TopMargin");
            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");
            this.BottomMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("BottomMargin");
            this.ReportHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportHeaderBand>("ReportHeader");
            this.PageFooter = reportInitializer.GetControl<DevExpress.XtraReports.UI.PageFooterBand>("PageFooter");
            this.checkBox2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox2");
            this.checkBox1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox1");
            this.richText6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("richText6");
            this.richText3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("richText3");
            this.richText2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("richText2");
            this.table1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table1");
            this.richText17 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("richText17");
            this.pageBreak16 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageBreak>("pageBreak16");
            this.richText16 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("richText16");
            this.pageBreak15 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageBreak>("pageBreak15");
            this.richText15 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("richText15");
            this.pageBreak14 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageBreak>("pageBreak14");
            this.richText14 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("richText14");
            this.pageBreak13 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageBreak>("pageBreak13");
            this.richText13 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("richText13");
            this.pageBreak12 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageBreak>("pageBreak12");
            this.richText12 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("richText12");
            this.pageBreak11 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageBreak>("pageBreak11");
            this.richText11 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("richText11");
            this.pageBreak10 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageBreak>("pageBreak10");
            this.pageBreak9 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageBreak>("pageBreak9");
            this.pageBreak1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageBreak>("pageBreak1");
            this.richText1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("richText1");
            this.tableRow1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow1");
            this.tableRow2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow2");
            this.tableCell1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell1");
            this.richText4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("richText4");
            this.tableCell2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell2");
            this.richText5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("richText5");
            this.label97 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label97");
            this.pageInfo2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageInfo>("pageInfo2");
            this.label60 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label60");
            this.line2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("line2");
            this.pictureBox2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPictureBox>("pictureBox2");

            // Parameters
            this.applicationid = reportInitializer.GetParameter("applicationid");

            // Data Sources
            this.sqlDataSource1 = reportInitializer.GetDataSource<DevExpress.DataAccess.Sql.SqlDataSource>("sqlDataSource1");

            // Calculated Fields
            this.AppId = reportInitializer.GetCalculatedField("AppId");
            this.TreesFlag = reportInitializer.GetCalculatedField("TreesFlag");
            this.LawnsFlag = reportInitializer.GetCalculatedField("LawnsFlag");
            this.StreamsFlag = reportInitializer.GetCalculatedField("StreamsFlag");
            this.TopographFlag = reportInitializer.GetCalculatedField("TopographFlag");
            this.NaturalOthersFlag = reportInitializer.GetCalculatedField("NaturalOthersFlag");
            this.BenchesFlag = reportInitializer.GetCalculatedField("BenchesFlag");
            this.FencesFlag = reportInitializer.GetCalculatedField("FencesFlag");
            this.DrainInletsFlag = reportInitializer.GetCalculatedField("DrainInletsFlag");
            this.RoadsFlag = reportInitializer.GetCalculatedField("RoadsFlag");
            this.ParkingLotsFlag = reportInitializer.GetCalculatedField("ParkingLotsFlag");
            this.CurbsFlag = reportInitializer.GetCalculatedField("CurbsFlag");
            this.SignsFlag = reportInitializer.GetCalculatedField("SignsFlag");
            this.ArchaResFlag = reportInitializer.GetCalculatedField("ArchaResFlag");
            this.ManmadeOthersFlag = reportInitializer.GetCalculatedField("ManmadeOthersFlag");
            this.RoofCoveringFlag = reportInitializer.GetCalculatedField("RoofCoveringFlag");
            this.RoofSheathingFlag = reportInitializer.GetCalculatedField("RoofSheathingFlag");
            this.FlashingFlag = reportInitializer.GetCalculatedField("FlashingFlag");
            this.ChimneysFlag = reportInitializer.GetCalculatedField("ChimneysFlag");
            this.RoofPenetrationsFlag = reportInitializer.GetCalculatedField("RoofPenetrationsFlag");
            this.GuttersFlag = reportInitializer.GetCalculatedField("GuttersFlag");
            this.CorniceFlag = reportInitializer.GetCalculatedField("CorniceFlag");
            this.TrimFlag = reportInitializer.GetCalculatedField("TrimFlag");
            this.RoofOthersFlag = reportInitializer.GetCalculatedField("RoofOthersFlag");
            this.FacadesWallsFlag = reportInitializer.GetCalculatedField("FacadesWallsFlag");
            this.WindowFlag = reportInitializer.GetCalculatedField("WindowFlag");
            this.DoorFlag = reportInitializer.GetCalculatedField("DoorFlag");
            this.AttachmentsFlag = reportInitializer.GetCalculatedField("AttachmentsFlag");
            this.FoundationFlag = reportInitializer.GetCalculatedField("FoundationFlag");
            this.FacadesOthersFlag = reportInitializer.GetCalculatedField("FacadesOthersFlag");
            this.PorchesFlag = reportInitializer.GetCalculatedField("PorchesFlag");
            this.BalconiesFlag = reportInitializer.GetCalculatedField("BalconiesFlag");
            this.LightFixturesFlag = reportInitializer.GetCalculatedField("LightFixturesFlag");
            this.ApputrenancesOthersFlag = reportInitializer.GetCalculatedField("ApputrenancesOthersFlag");
            this.FloorsFlag = reportInitializer.GetCalculatedField("FloorsFlag");
            this.FinishesWallsFlag = reportInitializer.GetCalculatedField("FinishesWallsFlag");
            this.CeilingsFlag = reportInitializer.GetCalculatedField("CeilingsFlag");
            this.FinishesOthersFlag = reportInitializer.GetCalculatedField("FinishesOthersFlag");
            this.LandingsFlag = reportInitializer.GetCalculatedField("LandingsFlag");
            this.Molding_Trim = reportInitializer.GetCalculatedField("Molding_Trim");
            this.Steps_Stairs = reportInitializer.GetCalculatedField("Steps_Stairs");
            this.StepsFlag = reportInitializer.GetCalculatedField("StepsFlag");
            this.Molding_Trim1 = reportInitializer.GetCalculatedField("Molding_Trim1");
            this.DoorHardwareFlag = reportInitializer.GetCalculatedField("DoorHardwareFlag");
            this.DoorFrames_Flag = reportInitializer.GetCalculatedField("DoorFrames_Flag");
            this.WindowsHardwareFlag = reportInitializer.GetCalculatedField("WindowsHardwareFlag");
            this.WindowsFramesFlag = reportInitializer.GetCalculatedField("WindowsFramesFlag");
            this.OpeningOtherFlag = reportInitializer.GetCalculatedField("OpeningOtherFlag");
            this.DoorHardware1 = reportInitializer.GetCalculatedField("DoorHardware1");
            this.StairsFlag = reportInitializer.GetCalculatedField("StairsFlag");
            this.FireplacesFlag = reportInitializer.GetCalculatedField("FireplacesFlag");
            this.BuiltInFlag = reportInitializer.GetCalculatedField("BuiltInFlag");
            this.OtherFeaturesFlag = reportInitializer.GetCalculatedField("OtherFeaturesFlag");
            this.SiteFeaturesFlag = reportInitializer.GetCalculatedField("SiteFeaturesFlag");
            this.ExteriorFeatureFlag = reportInitializer.GetCalculatedField("ExteriorFeatureFlag");
            this.InteriorFeatureFlag = reportInitializer.GetCalculatedField("InteriorFeatureFlag");
            this.Condition1 = reportInitializer.GetCalculatedField("Condition1");
            this.Condition2 = reportInitializer.GetCalculatedField("Condition2");
        }
        private DevExpress.XtraReports.UI.TopMarginBand TopMargin;
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.BottomMarginBand BottomMargin;
        private DevExpress.XtraReports.UI.ReportHeaderBand ReportHeader;
        private DevExpress.XtraReports.UI.PageFooterBand PageFooter;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox2;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox1;
        private DevExpress.XtraReports.UI.XRRichText richText6;
        private DevExpress.XtraReports.UI.XRRichText richText3;
        private DevExpress.XtraReports.UI.XRRichText richText2;
        private DevExpress.XtraReports.UI.XRTable table1;
        private DevExpress.XtraReports.UI.XRRichText richText17;
        private DevExpress.XtraReports.UI.XRPageBreak pageBreak16;
        private DevExpress.XtraReports.UI.XRRichText richText16;
        private DevExpress.XtraReports.UI.XRPageBreak pageBreak15;
        private DevExpress.XtraReports.UI.XRRichText richText15;
        private DevExpress.XtraReports.UI.XRPageBreak pageBreak14;
        private DevExpress.XtraReports.UI.XRRichText richText14;
        private DevExpress.XtraReports.UI.XRPageBreak pageBreak13;
        private DevExpress.XtraReports.UI.XRRichText richText13;
        private DevExpress.XtraReports.UI.XRPageBreak pageBreak12;
        private DevExpress.XtraReports.UI.XRRichText richText12;
        private DevExpress.XtraReports.UI.XRPageBreak pageBreak11;
        private DevExpress.XtraReports.UI.XRRichText richText11;
        private DevExpress.XtraReports.UI.XRPageBreak pageBreak10;
        private DevExpress.XtraReports.UI.XRPageBreak pageBreak9;
        private DevExpress.XtraReports.UI.XRPageBreak pageBreak1;
        private DevExpress.XtraReports.UI.XRRichText richText1;
        private DevExpress.XtraReports.UI.XRTableRow tableRow1;
        private DevExpress.XtraReports.UI.XRTableRow tableRow2;
        private DevExpress.XtraReports.UI.XRTableCell tableCell1;
        private DevExpress.XtraReports.UI.XRRichText richText4;
        private DevExpress.XtraReports.UI.XRTableCell tableCell2;
        private DevExpress.XtraReports.UI.XRRichText richText5;
        private DevExpress.XtraReports.UI.XRLabel label97;
        private DevExpress.XtraReports.UI.XRPageInfo pageInfo2;
        private DevExpress.XtraReports.UI.XRLabel label60;
        private DevExpress.XtraReports.UI.XRLine line2;
        private DevExpress.DataAccess.Sql.SqlDataSource sqlDataSource1;
        private DevExpress.XtraReports.UI.CalculatedField AppId;
        private DevExpress.XtraReports.UI.CalculatedField TreesFlag;
        private DevExpress.XtraReports.UI.CalculatedField LawnsFlag;
        private DevExpress.XtraReports.UI.CalculatedField StreamsFlag;
        private DevExpress.XtraReports.UI.CalculatedField TopographFlag;
        private DevExpress.XtraReports.UI.CalculatedField NaturalOthersFlag;
        private DevExpress.XtraReports.UI.CalculatedField BenchesFlag;
        private DevExpress.XtraReports.UI.CalculatedField FencesFlag;
        private DevExpress.XtraReports.UI.CalculatedField DrainInletsFlag;
        private DevExpress.XtraReports.UI.CalculatedField RoadsFlag;
        private DevExpress.XtraReports.UI.CalculatedField ParkingLotsFlag;
        private DevExpress.XtraReports.UI.CalculatedField CurbsFlag;
        private DevExpress.XtraReports.UI.CalculatedField SignsFlag;
        private DevExpress.XtraReports.UI.CalculatedField ArchaResFlag;
        private DevExpress.XtraReports.UI.CalculatedField ManmadeOthersFlag;
        private DevExpress.XtraReports.UI.CalculatedField RoofCoveringFlag;
        private DevExpress.XtraReports.UI.CalculatedField RoofSheathingFlag;
        private DevExpress.XtraReports.UI.CalculatedField FlashingFlag;
        private DevExpress.XtraReports.UI.CalculatedField ChimneysFlag;
        private DevExpress.XtraReports.UI.CalculatedField RoofPenetrationsFlag;
        private DevExpress.XtraReports.UI.CalculatedField GuttersFlag;
        private DevExpress.XtraReports.UI.CalculatedField CorniceFlag;
        private DevExpress.XtraReports.UI.CalculatedField TrimFlag;
        private DevExpress.XtraReports.UI.CalculatedField RoofOthersFlag;
        private DevExpress.XtraReports.UI.CalculatedField FacadesWallsFlag;
        private DevExpress.XtraReports.UI.CalculatedField WindowFlag;
        private DevExpress.XtraReports.UI.CalculatedField DoorFlag;
        private DevExpress.XtraReports.UI.CalculatedField AttachmentsFlag;
        private DevExpress.XtraReports.UI.CalculatedField FoundationFlag;
        private DevExpress.XtraReports.UI.CalculatedField FacadesOthersFlag;
        private DevExpress.XtraReports.UI.CalculatedField PorchesFlag;
        private DevExpress.XtraReports.UI.CalculatedField BalconiesFlag;
        private DevExpress.XtraReports.UI.CalculatedField LightFixturesFlag;
        private DevExpress.XtraReports.UI.CalculatedField ApputrenancesOthersFlag;
        private DevExpress.XtraReports.UI.CalculatedField FloorsFlag;
        private DevExpress.XtraReports.UI.CalculatedField FinishesWallsFlag;
        private DevExpress.XtraReports.UI.CalculatedField CeilingsFlag;
        private DevExpress.XtraReports.UI.CalculatedField FinishesOthersFlag;
        private DevExpress.XtraReports.UI.CalculatedField LandingsFlag;
        private DevExpress.XtraReports.UI.CalculatedField Molding_Trim;
        private DevExpress.XtraReports.UI.CalculatedField Steps_Stairs;
        private DevExpress.XtraReports.UI.CalculatedField StepsFlag;
        private DevExpress.XtraReports.UI.CalculatedField Molding_Trim1;
        private DevExpress.XtraReports.UI.CalculatedField DoorHardwareFlag;
        private DevExpress.XtraReports.UI.CalculatedField DoorFrames_Flag;
        private DevExpress.XtraReports.UI.CalculatedField WindowsHardwareFlag;
        private DevExpress.XtraReports.UI.CalculatedField WindowsFramesFlag;
        private DevExpress.XtraReports.UI.CalculatedField OpeningOtherFlag;
        private DevExpress.XtraReports.UI.CalculatedField DoorHardware1;
        private DevExpress.XtraReports.UI.CalculatedField StairsFlag;
        private DevExpress.XtraReports.UI.CalculatedField FireplacesFlag;
        private DevExpress.XtraReports.UI.CalculatedField BuiltInFlag;
        private DevExpress.XtraReports.UI.CalculatedField OtherFeaturesFlag;
        private DevExpress.XtraReports.UI.CalculatedField SiteFeaturesFlag;
        private DevExpress.XtraReports.UI.CalculatedField ExteriorFeatureFlag;
        private DevExpress.XtraReports.UI.CalculatedField InteriorFeatureFlag;
        private DevExpress.XtraReports.UI.CalculatedField Condition1;
        private DevExpress.XtraReports.UI.CalculatedField Condition2;
        private DevExpress.XtraReports.Parameters.Parameter applicationid;
        private DevExpress.XtraReports.UI.XRPictureBox pictureBox2;
    }
}
