name: Build and deploy ASP.Net Core app to Azure Web App - api-greencounty-reports

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      # Checkout source code
      - name: Checkout
        uses: actions/checkout@v2

      # Install .NET 5 SDK  
      - name: Setup .NET 5 SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      # Restore NuGet packages
      - name: Restore dependencies
        run: dotnet restore ./PresTrustDevExReportsService/Src/APIs/PresTrust.DevExReports.API

      # Build the project
      - name: Build
        run: dotnet build ./PresTrustDevExReportsService/Src/APIs/PresTrust.DevExReports.API --configuration Release --no-restore

      # Publish the project
      - name: Publish
        run: dotnet publish ./PresTrustDevExReportsService/Src/APIs/PresTrust.DevExReports.API --configuration Release --output ./publish --no-restore

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v1
        with:
          app-name: 'api-greencounty-ostf'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_26D57BB4319940FDBF54323B6AD649CF }}
          package: ./publish




